spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**

        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**


        - id: service-discovery-route
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/dashboard
          filters:
            - SetPath=/

        - id: service-discovery-statics-route
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE